Repository agoda-com/Kakao, pull requests merged in 2019-10, with the labels that each got.

#165 Supporting EditText and child realization for KTextInputLayout
  kakao/src/main/kotlin/com/agoda/kakao/common/builders/ViewBuilder.kt
  kakao/src/main/kotlin/com/agoda/kakao/edit/KTextInputLayout.kt
Labels: 🐞 Bug, 🔜 Ready to merge

#169 Example with descendant interaction
  sample/src/androidTest/kotlin/com/agoda/sample/MultiTypeRecyclerTest.kt
  sample/src/androidTest/kotlin/com/agoda/sample/NestedRecyclerTest.kt
  sample/src/androidTest/kotlin/com/agoda/sample/SingleTypeRecyclerTest.kt
  sample/src/androidTest/kotlin/com/agoda/sample/TestActivityTest.kt
  sample/src/androidTest/kotlin/com/agoda/sample/screen/TestActivityScreen.kt
  sample/src/androidTest/kotlin/com/agoda/sample/screen/TestRecyclerScreen.kt
  sample/src/main/AndroidManifest.xml
  sample/src/main/kotlin/com/agoda/sample/ListActivity.kt
  sample/src/main/kotlin/com/agoda/sample/MultitypeRecyclerActivity.kt
  sample/src/main/kotlin/com/agoda/sample/NestedRecyclerAdapter.kt
  sample/src/main/kotlin/com/agoda/sample/RecyclerAdapter.kt
  sample/src/main/kotlin/com/agoda/sample/SingleTypeRecyclerActivity.kt
  sample/src/main/kotlin/com/agoda/sample/TestActivity.kt
  sample/src/main/kotlin/com/agoda/sample/multitypeAdapter/BaseDelegatesAdapter.kt
  sample/src/main/kotlin/com/agoda/sample/multitypeAdapter/ItemDelegate.kt
  sample/src/main/res/layout/activity_test.xml
  sample/src/main/res/layout/checkbox_item_recycler.xml
  sample/src/main/res/layout/text_item_recycler.xml
Labels: 🦄 Enhancement

#173 Update README.md
  README.md
Labels: ✏️ Typo, 🔜 Ready to merge

#171 Add KSwitch to allow swipe gestures on switches
  README.md
  kakao/src/main/kotlin/com/agoda/kakao/switch/KSwitch.kt
  kakao/src/main/kotlin/com/agoda/kakao/switch/SwitchableActions.kt
  sample/src/androidTest/kotlin/com/agoda/sample/TestActivityTest.kt
  sample/src/androidTest/kotlin/com/agoda/sample/screen/TestActivityScreen.kt
  sample/src/androidTest/kotlin/com/agoda/sample/screen/TestRecyclerScreen.kt
  sample/src/main/kotlin/com/agoda/sample/SingleTypeRecyclerActivity.kt
  sample/src/main/kotlin/com/agoda/sample/multitypeAdapter/BaseDelegatesAdapter.kt
  sample/src/main/kotlin/com/agoda/sample/multitypeAdapter/ItemDelegate.kt
  sample/src/main/res/layout/activity_test.xml
  sample/src/main/res/layout/checkbox_item_recycler.xml
Labels: 🦄 Enhancement

#180 Add tint support
  kakao/src/main/kotlin/com/agoda/kakao/common/matchers/DrawableMatcher.kt
  kakao/src/main/kotlin/com/agoda/kakao/image/ImageViewAssertions.kt
  sample/src/androidTest/kotlin/com/agoda/sample/DrawableListTest.kt
  sample/src/androidTest/kotlin/com/agoda/sample/TestActivityTest.kt
  sample/src/main/kotlin/com/agoda/sample/DrawableListActivity.kt
  sample/src/main/kotlin/com/agoda/sample/TestActivity.kt
  sample/src/main/res/layout/activity_test.xml
Labels: 🐞 Bug, 🔜 Ready to merge, 🦄 Enhancement

#181 Fix Java docs references to specific classes
  kakao/src/main/kotlin/com/agoda/kakao/drawer/KDrawerView.kt
  kakao/src/main/kotlin/com/agoda/kakao/image/KImageView.kt
  kakao/src/main/kotlin/com/agoda/kakao/text/KButton.kt
  kakao/src/main/kotlin/com/agoda/kakao/text/KTextView.kt
Labels: 🔜 Ready to merge, 🦄 Enhancement
